### ISSUE TITLE
repo code different from the code shown on youtube

### ISSUE THREAD

**Issue by jpainam** [leerob/nextjs-postgres-email-client#3]
Hi.
could you upload the version you shown on the youtube channel. This repo seems to be incomplete

On the repository. no `layout` and `[id]`
<img width="247" alt="Screenshot 2023-11-10 at 6 26 24 AM" src="https://github.com/leerob/nextjs-postgres-email-client/assets/1701705/e3057c8a-8b22-4e07-9546-bb8f2afaa893">

On the youtube channel, there are `layout.tsx` and `[id]` folder
<img width="265" alt="Screenshot 2023-11-10 at 6 26 51 AM" src="https://github.com/leerob/nextjs-postgres-email-client/assets/1701705/9a4d41eb-8466-4520-8998-ddacbebc5060">

**Comment by leerob** [comment]
I've pushed some changes since then, but you can view the git history if you want to see the initial version where I made the video!

**Comment by jpainam** [comment]
Got it [nextjs-postgres-email-client](https://github.com/leerob/nextjs-postgres-email-client/tree/a471722c67f5255c0485aa41b26a5c93f3ad2602)
